version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: ecommerce_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: